### ISSUE TITLE
Step across snake bodies when searching

### ISSUE THREAD

**Issue by chynl** [chuyangliu/snake#6]
When searching for the shortest path to food, take into account the fact that the snake frees squares as it moves.

**Comment by Noeland** [comment]
Here is my idea.
A snake consists of multiple blocks. Lets call them "body".
During the searching, if we meet a body block, there are two important numbers.
The first one is the number of body blocks from this particular body block to the tail. Let's call this distance A.
The other one is the length of the particular path connecting the starting point (which is the head) and this body block. Let's call this distance B.

If A<B, it is safe to step across this body block. This is because when the real snake comes to this location, it's head has moved for a distance of B and so does the tail.

**Comment by chynl** [comment]
That make sense. Thanks! @Noeland

**Comment by chynl** [comment]
The enhancement is considered not high enough.
